name: build
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu'
        run: sudo apt-get update && sudo apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev libdeflate-dev
      - name: Install autotools (macos)
        if: ${{ matrix.os == 'macos' }}
        run: brew install autoconf automake libdeflate xz
      - name: Build executable
        run: make
      - name: Run executable (help)
        run: samtools/samtools tanuki
      - uses: actions/upload-artifact@v4
        with:
          name: samtools-mruby-${{ matrix.os }}
          path: samtools/samtools
